### ISSUE TITLE
Please upload the code

### ISSUE THREAD

**Issue by kksinghal** [mxbi/dreamcoder-arc#1]

**Comment by MathisFederico** [comment]
Up

**Comment by watts4speed** [comment]
It's great to have cleaned up code.  Even if it's not so clean code it's better than no code. :-)

**Comment by MathisFederico** [comment]
> It's great to have cleaned up code.  Even if it's not so clean code it's better than no code. :-)

I would by happy to clean it up myself tbh, but it has to be open-sourced for that

**Comment by mxbi** [comment]
Hey @kksinghal @MathisFederico @watts4speed thank you for the patience and for the nagging! 😄 

I've uploaded the code now - let me know if you run into any issues!
