### ISSUE TITLE
 Build Failure in Singularity Container Due to Conda and System Library Conflicts

### ISSUE THREAD

**Issue by KohsukeIde** [mxbi/dreamcoder-arc#3]
I encountered a build failure while trying to create a Singularity container using the provided Singularity definition file. The error occurs when attempting to install the vose package via pip within the Conda environment. The build fails due to a linker error that seems to be caused by conflicts between Conda's custom toolchain and the system libraries (libm.so.6 and libmvec.so.1).

```
Error during Singularity container build when installing `vose` package:

  /usr/local/conda/compiler_compat/ld: /lib/x86_64-linux-gnu/libmvec.so.1: unknown type [0x13] section .relr.dyn'
  /usr/local/conda/compiler_compat/ld: skipping incompatible /lib/x86_64-linux-gnu/libmvec.so.1 when searching for /lib/x86_64-linux-gnu/libmvec.so.1
  /usr/local/conda/compiler_compat/ld: cannot find /lib/x86_64-linux-gnu/libmvec.so.1
  collect2: error: ld returned 1 exit status
  error: command '/usr/bin/g++' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for vose
Failed to build vose
ERROR: Could not build wheels for vose which use PEP 517 and cannot be installed directly
FATAL:   While performing build: while running engine: exit status 1
```

## Possible Solutions Tried:
Attempted to override Conda’s toolchain by setting CC, CXX, and LD to system binaries, but the issue persists.
Considered manually building vose within the container but encountered similar issues due to the interaction with Conda’s environment.

## Request:
Could you provide guidance on how to properly configure the Singularity container to avoid this conflict? Alternatively, are there any known workarounds or patches that could be applied to the Singularity definition to ensure compatibility with Conda's toolchain and system libraries?

Thank you for your assistance!

**Comment by mxbi** [comment]
Hey, thanks for the detailed issue!

My first guess is that this might be due to an upstream update in the `ubuntu` image perhaps, which changed the system libraries. I'm not a singularity expert, but if we take a look at the working image I have locally:

```
$ singularity inspect container.img
[...]
org.opencontainers.image.ref.name: ubuntu
org.opencontainers.image.version: 22.04
```
So it was built with ubuntu 22.04, whereas I can see that [`latest` points to 24.04](https://hub.docker.com/_/ubuntu).

I'm trying a build changing line 3 in the singularity file to `From: ubuntu:22.04`, will let you know if that works!

**Comment by KohsukeIde** [comment]
I changed my line 3 to `From: ubuntu:22.04`
and it seems like it's working fine! thx!

also, I think you have to run 
` singularity run --nv ../container_mod.img python -u arcbin/arc_mikel2.py -c 76 -t 3600 -R 2400 -i 1`
to use GPU for recognition model?

**Comment by mxbi** [comment]
Great, thank you. I'll add that to the repo.

As for GPU, the code doesn't support GPU so passing one through to the container shouldn't make a difference (unless you change the code too). I think the model is sufficiently small that it wouldn't help much. Of course, that might be useful if you make changes.
